environments:
  dev:
    envName: dev
    webUrl: http://automationpractice.com/
    title: automationPractice
    browser: firefox
    userEmail: test@test.pl
    userPassword: testtest
    loginFailMessage: Authentication failed.
    active: y
  test:
    envName: test
#    webUrl: http://146.59.32.4/
    webUrl: http://automationpractice.com/
    title: selenium-advance
    browser: chrome
    userEmail: test@test.pl
    userPassword: testtest
    loginFailMessage: Authentication failed.
    active: n


